### ISSUE TITLE
New Firebase Console

### ISSUE THREAD

**Issue by kiley0** [joeeames/AngularFireCourse#1]
At Google I/O in May 2016, they announced a pretty hefty expansion of the Firebase suite including a brand new Console.  While a lot of the Firebase code in this course will work just fine, the videos that show how to use the old Firebase console may need to be updated to the new Firebase console.

![firebase_new_console](https://cloud.githubusercontent.com/assets/3933881/15511918/7f857e90-21ab-11e6-91c7-fda48b093865.png)

**Comment by joeeames** [comment]
Thanks for the note. I'll be scheduling an update to this course soon.
